---

- name: enable repo_gpgcheck for updates
  when: ansible_distribution_major_version > 7
  include_role:
    name: yum/repo-setting
  vars:
    _file: CentOS-Base
    _repo: updates
    _option: repo_gpgcheck
    _value: 0
