---

- debug: var=yum
  tags:
    - never
    - debug

- debug: msg={{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml
  tags:
    - never
    - debug

- name: set os version specific variables
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      errors: ignore

- debug: var=yum
  tags:
    - never
    - debug

- name: distribution specific things
  include: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
      errors: ignore

- name: keys are imported
  when: yum_import_keys
  rpm_key:
    key: "{{yum.rpmkeys_uri}}/{{ item }}"
    state: present
  with_items: "{{ yum.rpmkeys }}"

- debug: var=ansible_pkg_mgr
  tags:
    - never
    - debug

# we have a chicken and egg situation here
# if yum is the default package manager, it is installed
# but maybe it is not functional, e.g. proxy settings
# therefore we skip this conditionally
#
- name: yum is configured
  when: ansible_pkg_mgr == 'yum'
  template:
    src: "{{ item }}"
    dest: /etc/yum.conf
    backup: true
  with_first_found:
    - "{{ playbook_dir }}/files/{{ cfg }}"
    - "{{ playbook_dir }}/templates/{{ cfg }}.j2"
    - "{{ yum_cfg }}.j2"

# we have a chicken and egg situation here
# if yum is the default package manager, it is installed
# but maybe it is not functional, e.g. proxy settings
# therefore we skip this conditionally
#
- name: yum is installed
  when: ansible_pkg_mgr != 'yum'
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - yum
    - pygpgme

- name: yum is configured
  when: ansible_pkg_mgr != 'yum'
  template:
    src: "{{ item }}"
    dest: /etc/yum.conf
    backup: true
  with_first_found:
    - "{{ playbook_dir }}/files/{{ cfg }}"
    - "{{ playbook_dir }}/templates/{{ cfg }}.j2"
    - "{{ yum_cfg }}.j2"

- name: plugins are installed
  package:
    name: yum-plugin-versionlock
    state: present
