---

- name: yum config
  template:
    src: "{{ item }}"
    dest: /etc/yum.conf
  with_first_found:
    - "{{ playbook_dir }}/files/{{ cfg }}"
    - "{{ playbook_dir }}/templates/{{ cfg }}.j2"
    - "{{ yum_cfg }}.j2"

- name: plugins are installed
  package:
    name: yum-plugin-versionlock
    state: present
