
- debug: var=reponame
  tags:
    - never
    - debug

- name: yum repo file exists
  yum_repository:
    name: "{{ reponame }}"
    description: "{{ description }}"
    baseurl: "{{ baseurl }}"
    enabled: "{{ enabled }}"
    gpgcheck: "{{ gpgcheck }}"
    gpgkey: "{{ gpgkey }}"
